### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by elevenfive**
- Solves NDK error "No toolchains found ... mips64el-linux-android"

### CODE REVIEW

**Comment by elevenfive** [comment]
@benjamin-bader Would you mind merging this and #53 & releasing?

**Comment by benjamin-bader** [comment]
@elevenfive I don't have commit rights here.  @philippb can, though!

**Comment by philippb** [comment]
Thank you @elevenfive for providing this and @benjamin-bader for reviewing. Merging now and cutting a release.

**Comment by elevenfive** [comment]
Thanks @philippb for releasing!

**Comment by philippb** [comment]
Thanks for your input!

**Pull request merged**
