### PR TITLE
Upgrade Gradle and the Android Gradle plugin

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Amongst other changes the new Android Gradle plugin version supports
automatic download of missing SDK dependencies. For detailed release notes
see:
https://developer.android.com/studio/releases/gradle-plugin.html

For the Gradle release notes see:
https://docs.gradle.org/4.0/release-notes.html

### CODE REVIEW

**Comment by sschuberth** [comment]
I'm interested in this change, too. @xiphirx any chance to get a release with this soon?

**Comment by papcio28** [comment]
Seems safe and IMO would be nice to include it in next release to provide users up-to-date dependencies - less risk of deps conflicts in projects.

Looking forward for some updates.

**Comment by ajalt** [comment]
Now that the release version of the new build tools is out, I updated Relinker to use them.

Version 1.2.3 should be available shortly.

**Comment by sschuberth** [comment]
@ajalt, I believe the changes in `ReLinkerInstanceTest.java` from this PR are still missing, though.

**Comment by ajalt** [comment]
Great catch, thank you! I added the missing fix in 2a6affe.

**Pull request closed without merging**
