### PR TITLE
Enable uploading to Maven Central

### PR DESCRIPTION
**Pull request by barnhill**
- Adds capability to upload to Maven Central
- Updates gradle (this also auto updates the gradlew and other included wrapper files)
- Update dependencies

Fixes https://github.com/KeepSafe/ReLinker/issues/79

### CODE REVIEW

**Comment by emarc-m** [comment]
@barnhill, thanks for this PR. I based my PR https://github.com/KeepSafe/ReLinker/pull/81 from this.

I'd like to request the following changes:
* Please update the PR when https://github.com/KeepSafe/ReLinker/pull/81 has been merged
* Please update this PR to only keep the updates for gradle and the dependency related changes

Kindly assign me as a reviewer after. Thank you.

**Comment by barnhill** [comment]
How about I just create a new branch after yours merges as it'll be easier since there is a lot to undo in here if the publishing is in another branch. 😎

**Comment by emarc-m** [comment]
@barnhill sounds good. Thank you.

**Comment by emarc-m** [comment]
Hi @barnhill I'm closing this PR for now. Kindly create a new one for the dependency updates. Thank you.

**Pull request closed without merging**
